# Generated by Django 4.0.1 on 2022-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Старый Учитель',
                'verbose_name_plural': 'Старые Учителя',
            },
        ),
    ]
